### ISSUE TITLE
Can we have an option in config file to specify interface using which we want to create gluster volume?

### ISSUE THREAD

**Issue by shekharberry** [gluster/gdeploy#12]
As of now gluster volume is being created using hostname specified under [hosts]. But there can be a scenario (like in the case of geo-rep) where we want to access hosts using names specified under [hosts] but want to create gluster volume using different interface.
For example using gdeploy we craeted and got this:

```
Volume Name: mastervol
Type: Distribute
Volume ID: ce502594-9126-45e7-b899-b8f600aadb9c
Status: Started
Number of Bricks: 4
Transport-type: tcp
Bricks:
Brick1: gprfs037.sbu.lab.eng.bos.redhat.com:/gluster/brick/brick
Brick2: gprfs038.sbu.lab.eng.bos.redhat.com:/gluster/brick/brick
Brick3: gprfs039.sbu.lab.eng.bos.redhat.com:/gluster/brick/brick
Brick4: gprfs040.sbu.lab.eng.bos.redhat.com:/gluster/brick/brick
Options Reconfigured:
performance.readdir-ahead: on
cluster.enable-shared-storage: enable
```

In the above example the Bricks are coming from 1Gige interface defined under [hosts] but we want a configuration where we define interface, like in example below we manually created volume using 10Gige interface:

```
Volume Name: mastervol
Type: Distribute
Volume ID: ce502594-9126-45e7-b899-b8f600aadb9c
Status: Started
Number of Bricks: 4
Transport-type: tcp
Bricks:
Brick1: gprfs037-10ge:/gluster/brick/brick
Brick2: gprfs038-10ge:/gluster/brick/brick
Brick3: gprfs039-10ge:/gluster/brick/brick
Brick4: gprfs040-10ge:/gluster/brick/brick
Options Reconfigured:
performance.readdir-ahead: on
cluster.enable-shared-storage: enable
```

**Comment by satheesaran** [comment]
This requirement comes as part of multiple network interface support in gluster. This feature is also sometimes referred as 'Network Seggregation', where management traffic happens via one network ( probably lesser bandwidth ) & data traffic movement happens with other network.

So in this case, the host has multiple hostnames or IP ( identifier ) per interface and typically to form a trusted storage pool ( gluster cluster ), one should use one hostnames/IP and to create a volume we choose a different hostname/IP.

**Comment by sac** [comment]
Using ip address solves the problem. I will go ahead and close this issue, please re-open if the suggest does not solve the problem.

**Comment by adampl** [comment]
@sac But how can I migrate existing volume from the initial network to the other?

**Comment by sac** [comment]
> @sac But how can I migrate existing volume from the initial network to the other?

@adampl that part is not covered in gdeploy.
