### ISSUE TITLE
adding channels should be done in one shot, if there are multiple channels

### ISSUE THREAD

**Issue by satheesaran** [gluster/gdeploy#120]
While adding more channels, gdeploy adds them one by one, which takes more time.
subscription-manager repos --enable=x
subscription-manager repos --enable=y
subscription-manager repos --enable=z

Rather gdeploy could add channels in one shot
subscription-manager repos --enable=x --enable=y --enable=z

**Comment by devyanikota** [comment]
Closing this for now. Will add it as an RFE for future versions in the new design.
