### ISSUE TITLE
start the volume post setting the volume options

### ISSUE THREAD

**Issue by satheesaran** [gluster/gdeploy#121]
If the config file has volume section, along with 'volume options' mentioned, set all the volume options and start the volume.

**Comment by sac** [comment]
@satheesaran what is the difference? Just curious. I would like to know the advantages before I fix this.

**Comment by satheesaran** [comment]
Good question.
Take for example, If my requirement is to have a volume only with glusterfs native protocol access and I don't want NFS or CIFS, then I  will create a volume, disable nfs, disable cifs and then start the volume.

If I start the volume and then disable NFS, I have seen 2 disadvantages 
1. gluster NFS service is started and then killed, which is like a unnecessary
(I know the service is not required in advance, why do I start it and then stop it - Its a overhead )
2. Starting NFS service loads other services like rpc, rpc.auth.d, etc, which are not cleanedup
( I agree this should be bug with NFS cleanup process ) But this is like welcoming ghost guest, which may bring in other ghosts.

So, I felt its a good practice to set all the volume options ahead and start the volume, which is certain

@sac - what are your thoughts ?

**Comment by sac** [comment]
@satheesaran makes sense. Commit https://github.com/gluster/gdeploy/commit/2f97f312c3b64ed8b98c0ab77431def83e1cdcaa fixes the issue.
