### ISSUE TITLE
Feature: Configure ctdb in a multiple interface environment

### ISSUE THREAD

**Issue by sbhaloth** [gluster/gdeploy#140]
In an environment where we have configuration as follows:

nic1 : 10.x.x.x
nic2 : 192.168.121.x (nodes, ctdb volume to be on these nics)
nic3 : 192.168.100.x (VIP, ctdb public ip to be on these nics)

The hosts entries that we mention in conf file , it does ssh via that host and create volumes using the same.
In this case we need to have entry for nodes file as well where we can mention the IP's and these IP's should be used for creating ctdb vol as well.

**Comment by sac** [comment]
Fixed in master. Now the user can configure gdeploy with multiple interfaces by providing the data in variable: ctdb_nodes
