### ISSUE TITLE
Errors related to rpc-statd while running samba setup from gdeploy

### ISSUE THREAD

**Issue by sbhaloth** [gluster/gdeploy#142]
ver: gdeploy-2.1.dev1-9.noarch.rpm 

 On running the conf file with cifs mount following errors are seen which is related to nfs even though nfs is not enabled and running on the setup.

TASK: [Restart rpc-statd service] *********************************************
failed: [10.70.47.64] => {"failed": true}
msg: Job for rpc-statd.service failed because the control process exited with error code. See "systemctl status rpc-statd.service" and "journalctl -xe" for details.

**Comment by sac** [comment]
Fixed in master.
