### ISSUE TITLE
If mount point is already present gdeploy doesn't skip and throws error

### ISSUE THREAD

**Issue by sbhaloth** [gluster/gdeploy#143]
Ver:gdeploy-2.1.dev1-9.noarch.rpm 

 If mount point is already present, it is not skipping and failing with following error:
[Create the dir to mount the volume, skips if present] ******************
failed: [10.70.47.64] => (item=/mnt/smb) => {"failed": true, "item": "/mnt/smb", "parsed": false}
Traceback (most recent call last):
OSError: [Errno 17] File exists: '/mnt/smb'

**Comment by sac** [comment]
This error is due to stale mount points present. Now an error is thrown anyway. This is very much
needed because, the stale mount is anyway unusable. User has to unmount it manually or either via
gdeploy. This error will be ignored by gdeploy but will not be skipped.
