### ISSUE TITLE
Gluster volume options set is missing from samba/ctdb setup

### ISSUE THREAD

**Issue by sbhaloth** [gluster/gdeploy#144]
When smb_enable=yes is set , there are certain volume options which needs to be set which is not present currently.
These volume options needs to be added as per admin guide.
 gluster vol set test-vol1 server.allow-insecure on
 gluster vol set test-vol1 stat-prefetch off
 gluster vol set test-vol1 storage.batch-fsync-delay-usec 0

**Comment by sac** [comment]
Fixed in master.
