### ISSUE TITLE
There needs to be sleep before mounting with smb after the restart of glusterd

### ISSUE THREAD

**Issue by sbhaloth** [gluster/gdeploy#145]
vers:  gdeploy-2.1.dev1-9.noarch.rpm 
When smb_enable=yes , when the glusterd vol file is edited and glusterd is restarted there needs to be a sleep before we mount the volume as we are immediately mounting so it fails sometimes.

**Comment by sac** [comment]
A 30 second pause has been added. Fixed in master.
