### ISSUE TITLE
Volume is created using bricks only from one node if multiple bricks are present in each node

### ISSUE THREAD

**Issue by sbhaloth** [gluster/gdeploy#147]
If there are multiple bricks in one server and brick path is not provided in conf file then volume gets created using all the bricks from single server.
If brick path is provided then the peer probe itself fails.

**Comment by sac** [comment]
This has been fixed. Peer probe was failing because master was not being set. Commit https://github.com/gluster/gdeploy/commit/d126c061a fixes the issue.
