### ISSUE TITLE
RFE: Make changes in gdeploy ganesha setup wrt shared volume changes.

### ISSUE THREAD

**Issue by shashankraj** [gluster/gdeploy#149]
Following are the new steps which needs to be taken care with the current script:

1) Once the shared volume is created, create a folder named “nfs-ganesha” inside /var/run/gluster/shared_storage
2) Copy ganesha.conf and ganesha-ha.conf from /etc/ganesha to /var/run/gluster/shared_storage/nfs-ganesha
3) and then perform gluster nfs-ganesha enable

**Comment by shashankraj** [comment]
Other changes includes:

1) Changing the <HA_CONF_DIR> path in add node, delete node and refresh config command.

new path is /var/run/gluster/shared_storage/nfs-ganesha

2) The volume export files location is also changed and needs to be modified wherever applicable:

new path is /var/run/gluster/shared_storage/nfs-ganesha/exports/

**Comment by sac** [comment]
Commit: https://github.com/gluster/gdeploy/commit/53b822743432522ff5836d16dd9da5e251a1de3b fixes the issue.
