### ISSUE TITLE
The glusterd vol file change is happening only on one node of cluster

### ISSUE THREAD

**Issue by sbhaloth** [gluster/gdeploy#153]
The option to be added /etc/glusterfs/glusterd.vol file has to be done on all the nodes of cluster.
Currently it is doing only on one node.
gdeploy-2.1.dev1-11.noarch

**Comment by sac** [comment]
Commit https://github.com/gluster/gdeploy/commit/2e9c14ed0c8c5c78c89fe8b784804233d14d401b fixes the issue.
