### ISSUE TITLE
unmount of volume after setfacl fails 

### ISSUE THREAD

**Issue by sbhaloth** [gluster/gdeploy#155]
Unmount of volume after doing setfacl fails with following error.

TASK: [Unmount the volumes] **************************************************\* 
failed: [10.70.42.11] => (item=/mnt/smb) => {"failed": true, "item": "/mnt/smb"}
msg: missing required arguments: src,fstype

**Comment by sac** [comment]
https://github.com/gluster/gdeploy/commit/27ab726dce6fdd2319c5b1e3db5343e6aebf5fe0 fixes the issue.
