### ISSUE TITLE
Need to provide sleep after glusterd restart before mounting the volume

### ISSUE THREAD

**Issue by sbhaloth** [gluster/gdeploy#156]
It gives errors randomly
TASK: [Mount the volumes] ****************************************************\* 
failed: [10.70.42.11] => (item=/mnt/smb) => {"failed": true, "item": "/mnt/smb"}
msg: Error mounting /mnt/smb: Mount failed. Please check the log file for more details.

FATAL: all hosts have already failed -- aborting

**Comment by sac** [comment]
Commit: https://github.com/gluster/gdeploy/commit/27ab726dce6fdd2319c5b1e3db5343e6aebf5fe0 fixes the issue
