### ISSUE TITLE
vg module has wrong documentation

### ISSUE THREAD

**Issue by mulbc** [gluster/gdeploy#250]
in https://github.com/gluster/gdeploy/blob/master/modules/vg.py the documentation is talking about options `vg_pattern` and `vg_name`, which is wrong.
`vg_pattern` is not used in the code and throws an error and `vg_name` is actually `vgname`

**Comment by sac** [comment]
Ack! Will fix this. Thanks.

**Comment by devyanikota** [comment]
PR #343 closes this issue.
