### ISSUE TITLE
thinpool chunksize configuration wrong

### ISSUE THREAD

**Issue by mulbc** [gluster/gdeploy#251]
According to https://github.com/gluster/gdeploy/blob/master/modules/lv.py#L268
the chunksize calculation for thin-pool in case of RAID 6 should be 256K - this is wrong.

Please consult https://access.redhat.com/documentation/en-US/Red_Hat_Storage/3.1/html/Administration_Guide/Brick_Configuration.html

**Comment by sac** [comment]
Ack! Will look into this and fix.

**Comment by sac** [comment]
@zeichenanonym the commit: https://github.com/gluster/gdeploy/commit/2455587e365c5e7 should fix the issue, requesting a review.

**Comment by mulbc** [comment]
not 100%:
a) The guide states a lower-case 'k' instead of 'K' - this makes a difference in the LVM layer.
b) For the calculation you are using an undocumented variable 'diskcount', which should be supplied. If this means "total number of disks in the RAID volume" then your calculation is wrong, because only the data disks should be used for the calculation.

**Comment by sac** [comment]
@zeichenanonym the guide refers in terms of KiB

> For example, for RAID 6 with 12 disks (10 data disks), stripe unit size should be chosen as 128 KiB. This leads to a full stripe size of 1280 KiB (1.25 MiB). The thin pool should then be created with the chunk size of 1280 KiB.

Which I think is `K', correct me if I'm wrong.

Regarding the `diskcount' variable the expectation is user provides data disks, which is documented in examples: https://github.com/gluster/gdeploy/blob/master/examples/gluster.conf.sample#L275

I will document in readthedocs, also that sample configuration needs a lot of clean up I will do that.

Sorry about the commit, I'll make amends once we conclude.

**Comment by mulbc** [comment]
I checked with the LVM developers and you are right! K and k are both KiB for --chunksize :)

No further issues from my side, providing that `diskcount` will be documented

**Comment by sac** [comment]
Thank you. I will document diskcount variable.

**Comment by mulbc** [comment]
Seeing that `diskcount` is now documented in the README I will close this issue
