### ISSUE TITLE
Creating 4x2 volume doesn't work...

### ISSUE THREAD

**Issue by kristvanbesien** [gluster/gdeploy#277]
I created a volume using this file:

[hosts]
gluster-{1..4}

[volume]
action=create
volname=sample3
replica=yes
replica_count=2
brick_dirs=/gluster/brick2/sample3,/gluster/brick3/sample3
force=yes

Without "force=yes" this fails. 

With "force=yes" the volume created looks like this:

Volume Name: sample3
Type: Distributed-Replicate
Volume ID: b3e656ea-c4eb-4852-aa4f-e4b74f29ab0b
Status: Started
Number of Bricks: 4 x 2 = 8
Transport-type: tcp
Bricks:
Brick1: gluster-1:/gluster/brick2/sample3
Brick2: gluster-1:/gluster/brick3/sample3
Brick3: gluster-2:/gluster/brick2/sample3
Brick4: gluster-2:/gluster/brick3/sample3
Brick5: gluster-3:/gluster/brick2/sample3
Brick6: gluster-3:/gluster/brick3/sample3
Brick7: gluster-4:/gluster/brick2/sample3
Brick8: gluster-4:/gluster/brick3/sample3
Options Reconfigured:
performance.readdir-ahead: on

This is not what I want...

I want to create a 4x2 volume where of course the second brick in a replica is on a different server. But how do you do this with gdeploy?

**Comment by sac** [comment]
Hi, 

If there is more than one brick in a node, gdeploy gets confused. The solution for this is to
mention the hosts:<brick path> in the brick_dirs variable under volume section.

[volume]
action=create
volname=foo
transport=tcp
replica_count=2
brick_dirs=<ip or host>:brick_dir,<ip or host>:brick_dir,<ip or host>:brick_dir ...

In your case:

brick_dirs=gluster-1:/gluster/brick2/sample3,gluster-2:/gluster/brick3/sample3 so on...

**Comment by devyanikota** [comment]
@kristvanbesien hello. Would you please take a minute and let us know if this issue is resolved.
Were you able to create a 4x2 volume by making changes as suggested above?
(we are cleaning up the backlog bugs in gdeploy). 
Thank you.

**Comment by kristvanbesien** [comment]
I've actually stopped using gdeploy and am doing everything with my own ansible playbooks. So you can close this as far as I am concerned.

**Comment by devyanikota** [comment]
ah! that's sad :(
Also, we are working on gluster-ansible repository where we are trying to keep gluster-specific roles here[1], you can take a look if that helps.
Am closing this issue. Thank you.
[1] https://github.com/gluster/gluster-ansible
