### ISSUE TITLE
Remove direct dependencies on python-markupsafe, PyYAML, python-jinja2

### ISSUE THREAD

**Issue by dpmramesh** [gluster/gdeploy#288]
gdeploy 2.0.1.X has following dependencies which are not yet available in EPEL. Ansible itself has dependencies on these packages but to slightly lower versions(which is available in upstream). Can we remove this direct dependencies if ansible itself can satisfy them?

Dependencies not available in upstream:
1. python-markupsafe >= 0.23
2. PyYAML >= 3.11 
3. python-jinja2 >= 2.7.3

**Comment by sac** [comment]
Commit: https://github.com/gluster/gdeploy/commit/e463787d1155d fixes the issue.
