### ISSUE TITLE
Provide flexibility to perform volume options on more than one volume for possible features

### ISSUE THREAD

**Issue by satheesaran** [gluster/gdeploy#296]
Provide the flexibility to perform operations on more than one volume, wherever possible.
For instance, user may required to stop more than one volumes. Currently this is not possible.

Actual:
[volume]
action=[stop,start,set]
volname=volume1

Expected:
[volume]
action=[stop, start, set]
volname=volume1, volume2,volume3

**Comment by satheesaran** [comment]
@sac what do you think ?

**Comment by sac** [comment]
@satheesaran this is a very good idea. I will look into this.

**Comment by devyanikota** [comment]
@satheesaran Closing this for now, will handle the same in the new design of gluster-ansible volume management. Thanks.
