### ISSUE TITLE
Modify existing pv module to conform to ansible standards

### ISSUE THREAD

**Issue by sac** [gluster/gdeploy#394]
Current pv module needs to be changed to conform to ansible standards.

Fix:
- Documentation (online and manual page)
- Convert the existing pv playbooks to roles
- Update pvcreate, pvremove, pvchange, pvresize

pvcreate:
 - pvcreate should support the following options:
   - force (-f)
   - uuid (-u)
   - zero (-Z)
   - metadatasize
   - dataalignment

pvremove:
   - force

pvchange:
   - all
   - uuid
   - metadataignore
   - allocatable

pvresize:
    - setphysicalvolumesize

**Comment by sac** [comment]
Sample invocation could be something like:

ansible rhgs-servers -m pv -a "action=create disk=sda zero=yes dataalignment=1024K"

via playbooks:

- name: Create physical volume on the given disks
  pv:   action: create disk: sda
          zero: yes 

or if more than one disk

- name: Create physical volume on the given disks
  pv:   action: create disk: sda
          zero: yes 
  with_items:
        - sda
        - sdb
        - sdc

**Comment by sac** [comment]
**DO NOT** forget to add documentation in the module. Set the DOCUMENTATION and EXAMPLES variables.

**Comment by devyanikota** [comment]
Closing this, as it will be handled in the new design of gluster-ansible under Gluster.infra role.
