### ISSUE TITLE
Modify the vg module to conform to ansible standards

### ISSUE THREAD

**Issue by sac** [gluster/gdeploy#395]
Update the existing vg module supporting actions:

- create
- remove
- extend
- convert
- reduce

vg with action=create should support the following options:

- maxlogicalvolumes
- maxphysicalvolumes
- physicalextentsize
- zero
- metadatasize
- dataalignment
- dataalignmentoffset

vg with action=extend should support options

- zero
- metadatasize
- metadataignore
- dataalignment
- dataalignmentoffset

vg with action=reduce should support:

- removemissing

**Comment by devyanikota** [comment]
Closing this, as it will be handled in the new design of gluster-ansible under Gluster.infra role.
