### ISSUE TITLE
Enhance the lv module and add more documentation

### ISSUE THREAD

**Issue by sac** [gluster/gdeploy#396]
Enhance the lv module to support:

**_lvcreate, lvchange, lvreduce, lvresize, lvconvert, lvextend, lvremove,  lvrename_**

_lvcreate - lv module with action=create should support the following options:_

* cachemode {passthrough|writeback|writethrough}
  Refer the admin guide for a default for cachemode
* chunksize ChunkSize[b|B|s|S|k|K|m|M|g|G]
* extents LogicalExtentsNumber[%{VG|PVS|FREE|ORIGIN}]
* poolmetadatasize MetadataVolumeSize[b|B|s|S|k|K|m|M|g|G]
* poolmetadataspare {y|n}
* size LogicalVolumeSize[b|B|s|S|k|K|m|M|g|G|t|T|p|P|e|E]
* stripesize StripeSize
* thin
* thinpool ThinPoolLogicalVolume{Name|Path}
* virtualsize VirtualSize[b|B|s|S|k|K|m|M|g|G|t|T|p|P|e|E]
* wipesignatures {y|n}
* zero {y|n}

_lvchange - lv module with action=change should support the following options:_

* errorwhenfull {y|n}
* permission {r|rw}
* zero {y|n}

_lvreduce - lv module with action=reduce should support the following options:_

* force
* extents [-]LogicalExtentsNumber[%{VG|LV|FREE|ORIGIN}]
* size [-]LogicalVolumeSize[bBsSkKmMgGtTpPeE]
* nofsck
* resizefs

_lvresize - lvmodule with action=resize should support the following options:_

* force
* nofsck
* resizefs
* extents [+|-]LogicalExtentsNumber[%{VG|LV|PVS|FREE|ORIGIN}]
* size [+|-]LogicalVolumeSize[bBsSkKmMgGtTpPeE]
* stripes Stripes
* poolmetadatasize [+]MetadataVolumeSize[bBsSkKmMgG]
* stripesize StripeSize

_lvconvert - lv module with action=convert should support the following options_

* cachepool CachePoolLogicalVolume{Name|Path}
* chunksize ChunkSize[b|B|s|S|k|K|m|M|g|G]
* cachesettings Key=Value
* poolmetadata PoolMetadataLogicalVolume{Name|Path}
* poolmetadatasize PoolMetadataSize[b|B|s|S|k|K|m|M|g|G]
* poolmetadataspare {y|n}
* stripesize StripeSize
* thin
* thinpool ThinPoolLogicalVolume{Name|Path}
* zero {y|n}

_lvextend - lv module with action=extend should support the following options_

* force
* extents [+]LogicalExtentsNumber[%{VG|LV|PVS|FREE|ORIGIN}]
* size [+]LogicalVolumeSize[bBsSkKmMgGtTpPeE]
* stripesize StripeSize
* nofsck
* resizefs

**Comment by sac** [comment]
Ensure to maintain backward compatibility.

**Comment by devyanikota** [comment]
Closing this, as it will be handled in the new design of gluster-ansible under Gluster.infra role.
