### ISSUE TITLE
Merge the volume-set module with gluster_volume

### ISSUE THREAD

**Issue by sac** [gluster/gdeploy#397]
Currently we have volume-set module, which is quite confusing, merge it with gluster_volume volume.

**Comment by devyanikota** [comment]
@ramkrsna @sankarshanmukhopadhyay I have added the 3.0 Label to the issues that were targetted for gdeploy v3.0.
Will be migrating them to the gluster-ansible repository, and then closing them.

**Comment by devyanikota** [comment]
Closing this, as it will be handled in the new design of gluster-ansible under Gluster.infra role.
