### ISSUE TITLE
Rename the volume module and enhance it

### ISSUE THREAD

**Issue by sac** [gluster/gdeploy#398]
Rename the volume module to glusterfs_volume (remember to symlink to volume.py so as not to break the backward compatibility for a few releases)

Enhance the glusterfs_volume module, should support the following features:

* volume  add-brick
* volume  attach-tier
* volume  barrier
* volume  bitrot
* volume  clear-locks
* volume  create
* volume  delete
* volume  detach-tier
* volume  geo-replication
* volume  heal
* volume  inode-quota
* volume  log
* volume  profile
* volume  quota
* volume  rebalance
* volume  remove-brick
* volume  replace-brick
* volume  reset
* volume  reset-brick
* volume  set
* volume  start
* volume  statedump
* volume  status
* volume  stop
* volume  sync
* volume  tier

See GlusterFS documentation for help regarding the above volume actions.

## The ansible module for volume

gluster_volume action=add-brick
gluster_volume action=attach-tier
gluster_volume action=barrier
gluster_volume action=bitrot
gluster_volume action=clear-locks
gluster_volume action=create
gluster_volume action=delete
gluster_volume action=detach-tier
gluster_volume action=geo-replication
gluster_volume action=heal
gluster_volume action=inode-quota
gluster_volume action=log
gluster_volume action=profile
gluster_volume action=quota
gluster_volume action=rebalance
gluster_volume action=remove-brick
gluster_volume action=replace-brick
gluster_volume action=reset
gluster_volume action=reset-brick
gluster_volume action=set
gluster_volume action=start
gluster_volume action=statedump
gluster_volume action=status
gluster_volume action=stop
gluster_volume action=sync
gluster_volume action=tier

And each action will take corresponding parameters as required by gluster

**Comment by devyanikota** [comment]
Will keep this issue marked as 'enhancement', this RFE will be handled in the new design of gluster-ansible under Gluster.infra role.
This issue can be thought of as the container issue for the new design of gluster_volume, where we handle the operation to be performed by using the 'action'/'state' variable.
