### ISSUE TITLE
Rename peer module to gluster_peer

### ISSUE THREAD

**Issue by sac** [gluster/gdeploy#402]
The module name peer is quite generic, rename it to gluster_peer. And enhance it by adding more comments and documentation.

**Comment by siddharthvipul** [comment]
https://github.com/gluster/gdeploy/pull/425
Please review

**Comment by devyanikota** [comment]
We are migrating roles to gluster-ansible, and consuming them from gluster/gadmin and others.
Hence, closing this issue against [gluster/gluster-ansible#13](https://github.com/gluster/gluster-ansible/issues/13)
