### ISSUE TITLE
example 2x2-volume-create-without-backend-setup.conf does not work

### ISSUE THREAD

**Issue by Daniel-Pivonka** [gluster/gdeploy#434]
Error: brick_dirs should be a directory inside mountpoint(/gluster/brick2).
Make sure relative paths for all the 2 mountpoints are given separately. Exiting!

the example seems to be missing the "mountpoints=...." line

**Comment by sac** [comment]
Ack! Commit https://github.com/gluster/gdeploy/commit/9d845f8d2 fixes the issue.

**Comment by sac** [comment]
@Daniel-Pivonka closing the issue. Please re-open if you think we need further fix.
