### ISSUE TITLE
Unable to create the gluster volume using gdeploy but backend is ok

### ISSUE THREAD

**Issue by mtridici** [gluster/gdeploy#436]
Hi all,

I'm trying to deploy a distributed disperse volume 2x(4+2) using gdeploy. Everything seems to work ok: backend is created, pvs, vgs, lvs and bricks but something was wrong during volume creation.
So I cannot start the volume and so on...
As you can see from the following output there is an error during this step.
Anyway, If I use the "gluster volume create" command specifying the same bricks of gdeploy config file it works without any problem! I'm using gdeploy-2.0.2-14 version.
Is there a stable and suggested version of gdeploy.
Thank you in advance.
Mauro

[root@glu01 tmpg931C1]# ansible-playbook -v -i ansible_hosts gluster-volume-create.yml 
Using /etc/ansible/ansible.cfg as config file

PLAY [master] **********************************************************************************************************************************************

TASK [Creates a volume] ************************************************************************************************************************************
fatal: [glu03-stg]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to glu03-stg closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_lXWmp6/ansible_module_volume.py\", line 318, in <module>\r\n    Volume(module)\r\n  File \"/tmp/ansible_lXWmp6/ansible_module_volume.py\", line 153, in __init__\r\n    self.gluster_volume_ops()\r\n  File \"/tmp/ansible_lXWmp6/ansible_module_volume.py\", line 253, in gluster_volume_ops\r\n    self.get_host_names()\r\n  File \"/tmp/ansible_lXWmp6/ansible_module_volume.py\", line 175, in get_host_names\r\n    self.hosts = literal_eval(hosts)\r\n  File \"/usr/lib64/python2.7/ast.py\", line 80, in literal_eval\r\n    return _convert(node_or_string)\r\n  File \"/usr/lib64/python2.7/ast.py\", line 79, in _convert\r\n    raise ValueError('malformed string')\r\nValueError: malformed string\r\n", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/tmp/tmpg931C1/gluster-volume-create.retry

PLAY RECAP *************************************************************************************************************************************************
glu03-stg                  : ok=0    changed=0    unreachable=0    failed=1

**Comment by sac** [comment]
@mtridici if you are using the gluster-volume-create.yml directly you have to ensure that you set the variables right. Can you share your variables file?

**Comment by mtridici** [comment]
Hi @sac , thank you very much for your reply.
In attachment you can find 3 files:
- the gdeploy configuration file (disperse_2x4+2.conf)
- the variables file (groupvar_all.txt)
- the output of "gluster volume info" command after volume creation (using gluster volume create command)

Thank you in advance.
[disperse_2x4+2.txt](https://github.com/gluster/gdeploy/files/1266911/disperse_2x4.2.txt)
[groupvar_all.txt](https://github.com/gluster/gdeploy/files/1266912/groupvar_all.txt)
[gluster_volume_info.txt](https://github.com/gluster/gdeploy/files/1266914/gluster_volume_info.txt)

**Comment by sac** [comment]
@mtridici thanks. @devyanikota will look into this and get back to you.

**Comment by mtridici** [comment]
I would add another info that could be useful: usually I execute gdeploy with -k option and, if something goes wrong, I change directory in /tmp/tmpblabla and I run ansible-playbook manually to "debug" the yml code. The gluster-volume-create.yml  should read the variables that gdeploy previuosly set... if I understand...

**Comment by mtridici** [comment]
@sac thank you very much for your support!

**Comment by sac** [comment]
@mtridici that is right, gluster-volume-create.yml should have worked. @devyanikota worked on a similar issue recently. She will help you debug the issue.

**Comment by mtridici** [comment]
I see that @devyanikota self-assigned this task :-) many thanks to all of you. I will wait for some news. Have a good week-end

**Comment by devyanikota** [comment]
Hi @mtridici good $time_of_the_day.
You can change the 'action' field to 'create', instead of 'mount', in your group_var/all file.
I have pasted my:
[group_vars/all](https://paste.opensuse.org/22865003) file,
[distributed-disperse.yml](https://paste.opensuse.org/58531707) file, and
output of [gluster_volume_info](https://paste.opensuse.org/74592695).
Hope this helps :)

**Comment by mtridici** [comment]
Hi @devyanikota, thank you very much for your support. 
Anyway, I'm sorry but I don't understand how I can "translate" your suggestion in "gdeploy configuration file changes" :-)
When I executed "gdeploy -vv -k -c dist_disperse_2x4+2.txt, backend is ok, but volume creation is not created (in attachment dist. disperse config file); what I have to change in my config file in order to create the volume automatically and wthout error?

I don't know if you can see my first message in this thread: it contains more details about the issue. If you need it I could copy & paste it here again.

Thank you again,
Mauro



[dist_disperse_2x4+2.txt](https://github.com/gluster/gdeploy/files/1277039/dist_disperse_2x4.2.txt)

**Comment by devyanikota** [comment]
Hi, @mtridici I provided info about changing the 'action' field in the ansible playbook with respect to your comment1 :)
I tried creating a distributed-disperse volume using the gdeploy config file, it works for me.
You can change the format of the mount-points in your configuration file, where you are appending the hostname along with the path of the mount point. You needn't do that!
For example: 
`mountpoints=/mnt/brick1,/mnt/brick2`
Same goes for the 'bricks' field. This should solve your issue.

**Comment by mtridici** [comment]
Hi @devyanikota,

you're right! :-) mea culpa! I'm a newbie and I'm creating a little bit of confusion. I hope you can forgive me. Unfortunately, I made the changes you kindly suggested but the problem still occurs.
I'll try to explain in a better way what I'm doing, why and the issue that I'm experiencing.

That's exactly the sequence of actions:

1) download and installation of gdeploy (master version)
2) creation of dist_disperse_2x4+2_devianykota.conf file (I attached it to this message)
3) run of "nohup gdeploy -vv -k -c dist_disperse_2x4+2_devianykota.conf &": 

	3.1) backend is created correctly on all the hosts (the "df" output is the same on all hosts):
	
/dev/mapper/gluster_vge-gluster_lve   88M  4,8M     83M   6% /gluster/mnt4
/dev/mapper/gluster_vgm-gluster_lvm   88M  4,8M     83M   6% /gluster/mnt12
/dev/mapper/gluster_vgh-gluster_lvh   88M  5,0M     83M   6% /gluster/mnt7
/dev/mapper/gluster_vgj-gluster_lvj   88M  4,8M     83M   6% /gluster/mnt9
/dev/mapper/gluster_vgc-gluster_lvc   88M  5,0M     83M   6% /gluster/mnt2
/dev/mapper/gluster_vgk-gluster_lvk   88M  4,8M     83M   6% /gluster/mnt10
/dev/mapper/gluster_vgg-gluster_lvg   88M  4,8M     83M   6% /gluster/mnt6
/dev/mapper/gluster_vgb-gluster_lvb   88M  5,0M     83M   6% /gluster/mnt1
/dev/mapper/gluster_vgl-gluster_lvl   88M  4,8M     83M   6% /gluster/mnt11
/dev/mapper/gluster_vgd-gluster_lvd   88M  4,8M     83M   6% /gluster/mnt3
/dev/mapper/gluster_vgi-gluster_lvi   88M  5,0M     83M   6% /gluster/mnt8
/dev/mapper/gluster_vgf-gluster_lvf   88M  4,8M     83M   6% /gluster/mnt5

	3.2) but no volume is created:
	
[root@glu01 tmplOmHgS]# gluster volume info
No volumes present

gdeploy try to start the volume but the volume doesn't exist (as you can see from the attached gdeploy_log.txt)

"TASK [Creates a Trusted Storage Pool] ******************************************
task path: /tmp/tmpKQVnTC/gluster-peer-probe.yml:7
changed: [glu01-stg] => {"changed": 1, "rc": 0}

TASK [Pause for a few seconds] *************************************************
task path: /tmp/tmpKQVnTC/gluster-peer-probe.yml:12
Pausing for 5 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)

ok: [glu01-stg] => {"changed": false, "delta": 5, "rc": 0, "start": "2017-09-05 14:19:13.839113", "stderr": "", "stdout": "Paused for 5.0 seconds", "stop": "2017-09-05 14:19:18.839289", "user_input": ""}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************
glu01-stg                  : ok=2    changed=1    unreachable=0    failed=0   

Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: gluster-volume-start.yml *********************************************
1 plays in /tmp/tmpKQVnTC/gluster-volume-start.yml

PLAY [master] ******************************************************************
META: ran handlers

TASK [Starts a volume] *********************************************************
task path: /tmp/tmpKQVnTC/gluster-volume-start.yml:7
fatal: [glu01-stg]: FAILED! => {"changed": false, "failed": true, "failed_when_result": true, "msg": "volume start: coldtier: failed: Volume coldtier does not exist\n", "rc": 1}
	to retry, use: --limit @/tmp/tmpKQVnTC/gluster-volume-start.retry

PLAY RECAP *********************************************************************
glu01-stg                  : ok=0    changed=0    unreachable=0    failed=1   "

At thi s point I think that something goes wrong during volume creation.
So, I decide to check the /tmp/tmpKQVnTC content (you can find group_vars_all file in attachment). 

Everything seems to be ok, so, in order to debug the gluster volume creation I try to execute the following command (in /tmp/tmpKQVnTC) but I receive this error:

[root@glu01 tmpKQVnTC]# ansible-playbook -v -i ansible_hosts gluster-volume-create.yml 
Using /etc/ansible/ansible.cfg as config file

PLAY [master] *****************************************************************************************************************************************************

TASK [Creates a volume] *******************************************************************************************************************************************
fatal: [glu03-stg]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to glu03-stg closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_mQCBtb/ansible_module_volume.py\", line 318, in <module>\r\n    Volume(module)\r\n  File \"/tmp/ansible_mQCBtb/ansible_module_volume.py\", line 153, in __init__\r\n    self.gluster_volume_ops()\r\n  File \"/tmp/ansible_mQCBtb/ansible_module_volume.py\", line 253, in gluster_volume_ops\r\n    self.get_host_names()\r\n  File \"/tmp/ansible_mQCBtb/ansible_module_volume.py\", line 175, in get_host_names\r\n    self.hosts = literal_eval(hosts)\r\n  File \"/usr/lib64/python2.7/ast.py\", line 80, in literal_eval\r\n    return _convert(node_or_string)\r\n  File \"/usr/lib64/python2.7/ast.py\", line 79, in _convert\r\n    raise ValueError('malformed string')\r\nValueError: malformed string\r\n", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/tmp/tmpKQVnTC/gluster-volume-create.retry

PLAY RECAP ********************************************************************************************************************************************************
glu03-stg                  : ok=0    changed=0    unreachable=0    failed=1   

In order to simplify the debug actions, I created a configuration file with the volume creation instructions only (create_volume_only.txt attached file) and I executed it using gdeploy but I obtained the same error during volume start since no volume has been created.

So, I move again in /tmp/tmpDfcdCY and I try to execute the following command:

[root@glu01 tmpDfcdCY]# ansible-playbook -v -i ansible_hosts gluster-volume-create.yml 
Using /etc/ansible/ansible.cfg as config file

PLAY [master] *****************************************************************************************************************************************************

TASK [Creates a volume] *******************************************************************************************************************************************
changed: [glu01-stg] => {"changed": 1, "rc": 0, "stdout": "volume create: coldtier: success: please start the volume to access data\n", "stdout_lines": ["volume create: coldtier: success: please start the volume to access data"]}

PLAY RECAP ********************************************************************************************************************************************************
glu01-stg                  : ok=1    changed=1    unreachable=0    failed=0   

THE VOLUME IS CREATED!

Can you help me to debug this strange behaviour? 
Can I ask you the OS, gdeploy and ansible version you are using?

Thank you very much for your patience,
Mauro

[create_volume_only.txt](https://github.com/gluster/gdeploy/files/1278174/create_volume_only.txt)
[dist_dispersed_2x4+2_devyanikota.txt](https://github.com/gluster/gdeploy/files/1278172/dist_dispersed_2x4.2_devyanikota.txt)
[gdeploy_logs.txt](https://github.com/gluster/gdeploy/files/1278173/gdeploy_logs.txt)
[group_vars_all_file.txt](https://github.com/gluster/gdeploy/files/1278171/group_vars_all_file.txt)

**Comment by mtridici** [comment]
Hi @devyanikota,

thanks to your support, I detected the cause of the strange behaviour: an hidden character in the "volume" section was creating the issue. So, I deleted and recreated the volume section applying also the changes you suggested (no hostname added to the mountpoint path).
Now, the gdeploy script works (you can find it in attachment)! :-) 
If possible, could you please check the script and let me know if it is ok from your point of view?
Executing the gdeploy script I'm obtaining a gluster volume distributed disperse 6x(4+2) (36 bricks, 12 bricks per server). From a fault tolerance point of view, do you think that is the best configuration for a cluster based on 3 servers (each server contains 12 hdd)?

Thank you very much.
Have a good day,
Mauro

[distributed_disperse_6x4+2_final_20170906.txt](https://github.com/gluster/gdeploy/files/1280320/distributed_disperse_6x4.2_final_20170906.txt)

**Comment by devyanikota** [comment]
Hey @mtridici glad to know that the config file worked for you :)
I checked the script but I haven't worked much with the performance of volumes,
I think the [gluster mailing list](https://lists.gluster.org/mailman/listinfo) would be a good place for this question. You can drop a mail to either gluster-users or gluster-devel.
Hope this helps.

**Comment by sac** [comment]
@mtridici if your issue is resolved, we can close this one?

**Comment by mtridici** [comment]
@sac yes, my issue has been solved, so you can close it. thanks to everyone.
