### ISSUE TITLE
Fails to set up a geo-replication session using gdeploy.

### ISSUE THREAD

**Issue by devyanikota** [gluster/gdeploy#479]
Downstream RFE BZ [1], [2].
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1475724
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1511491

**Comment by sankarshanmukhopadhyay** [comment]
@ramkrsna you'll probably have to file a bug to ask for merge rights on this repository. https://bugzilla.redhat.com/enter_bug.cgi?product=GlusterFS&component=project-infrastructure
