### ISSUE TITLE
Install.MD is missing information on needed packages

### ISSUE THREAD

**Issue by mykaul** [gluster/gdeploy#48]
At least on CentOS, to complete the pip install requirements, one needs to install both gcc and python-devel

'yum install -y gcc python-devel' works.

**Comment by nandajavarma** [comment]
@mykaul Thank you for reporting this. I will update the installation guide ASAP to reflect this requirement.

**Comment by nandajavarma** [comment]
@mykaul As these packages are usually present in development environments (and assuming that the forks will be made for development environments) this dependency was taken for granted. 
I have updated the INSTALL.md in this commit: https://github.com/gluster/gdeploy/commit/efdc7b38375dc65ae2bb4818963df0132ef203a5
Thanks again for reporting.
