### ISSUE TITLE
Change xfs settings when vdo volume is used.

### ISSUE THREAD

**Issue by devyanikota** [gluster/gdeploy#483]
Use these xfs settings for XFS in RHHI, so that XFS handle conditions when VDO runs out of physical space.

echo 4 | tee /sys/fs/xfs/dm-13/error/metadata/ENOSPC/max_retries
echo 4 | tee /sys/fs/xfs/dm-13/error/metadata/EIO/max_retries

**Comment by ramkrsna** [comment]
https://github.com/gluster/gdeploy/pull/505 Closes the issue.
