### ISSUE TITLE
Unable to set VDO writepolicy to auto

### ISSUE THREAD

**Issue by devyanikota** [gluster/gdeploy#488]
Using gdeploy,unable to set the writePolicy of VDO volume to 'auto'. Gdeploy allows the value of 'sync' & 'async' for writePolicy
Expected results: gdeploy should allow setting the value of writePolicy as 'auto'

**Comment by ramkrsna** [comment]
https://github.com/gluster/gdeploy/pull/497 tries to resolve the issue.  This needs to be installed with ansible-2.5 / ansible-engine-2.5 and above.

**Comment by devyanikota** [comment]
Merged #497 . Closing this issue.
