### ISSUE TITLE
gdeploy does not have a logging to file option

### ISSUE THREAD

**Issue by mykaul** [gluster/gdeploy#49]
When you are automatically using gdeploy, it should be able to put its logs (stdout/stderr) to a log file.
Today you can enable '-vv' but not a file where to output this for post inspection.

**Comment by nandajavarma** [comment]
This requirement can be addressed in the next release. Thanks for reporting.

**Comment by sac** [comment]
This can now be enabled by setting log_path in "/etc/ansible/ansible.cfg" ... the complete cli output will be logged. We are enhancing the gdeploy log as well, which will log every operation of gdeploy.
