### ISSUE TITLE
Add feature to tear down a setup with given config file

### ISSUE THREAD

**Issue by nkhare** [gluster/gdeploy#5]
For testing it is important to the setup the environment quickly.  Sometimes we would like to tear down the setup and set it up again. In such cases having a feature to team down the setup with given config file would be handy.

**Comment by nandajavarma** [comment]
This feature can be added in the next release.
Right now this can be done in a hard way as follows:
say, your conig file is named gluster.conf
Run from the root of source repo:

`python glusterlib/playbook_gen.py gluster.conf`

This creates the host_vars/group_vars files, move playbooks to places where ansible can find it.

Then run:

`ansible-playbook -i /tmp/playbooks/ansible_hosts templates/factory-reset.yml`

**Comment by nandajavarma** [comment]
This feature is not supported right now. Will be rolled in with the next release.

**Comment by nandajavarma** [comment]
This feature is now available in gdeploy. https://github.com/gluster/gdeploy/blob/master/examples/gluster.conf.sample#L298
