### ISSUE TITLE
package_installs.conf contains internal Red Hat repositories

### ISSUE THREAD

**Issue by mykaul** [gluster/gdeploy#50]
Example: http://jenkins.lab.eng.blr.redhat.com/rhsc/hc/ ...

**Comment by nandajavarma** [comment]
This file got included in the repo by mistake. I have removed the file in https://github.com/gluster/gdeploy/commit/085f7c6690fb656663e7e01996c278c627bae58b. Thanks for noticing and reporting.

**Comment by sac** [comment]
This is a regression. Will fix it.

**Comment by sac** [comment]
Fixed in the commit  [d7abb2a](https://github.com/gluster/gdeploy/commit/d7abb2aaa6f708253c016ccb76f4d60145982c61)

**Comment by mscherer** [comment]
So, if this is fixed, any reason to not close the issue ?

**Comment by sac** [comment]
Commit: https://github.com/gluster/gdeploy/pull/158/commits/2ce3f55366e5854bfa4b5215639d909589761ba8 fixes the issue.
