### ISSUE TITLE
lvm2 is not mentioned as a prerequisite 

### ISSUE THREAD

**Issue by mykaul** [gluster/gdeploy#53]
gdeploy fails if lvm2 is not installed on the hosts (pvcreate fails)

**Comment by sac-urs** [comment]
I will add this as a dependency in the spec file.

**Comment by nandajavarma** [comment]
@gluster-deploy Similar to the firewalld bug, shall I close this?

**Comment by sac** [comment]
Commit: https://github.com/gluster/gdeploy/pull/158/commits/fc96e18eae5145f7fe14599773a4d80262a3548f fixes the issue.

**Comment by y0hnn** [comment]
@sac Should not it be lvm2py >= 1 ? https://pypi.python.org/pypi/lvm2py/

**Comment by sac** [comment]
@yohannprigent I meant the lvm2 package itself.

[sac@lisa ~]$ rpm -qa | grep lvm2
lvm2-2.02.116-3.fc22.x86_64
lvm2-libs-2.02.116-3.fc22.x86_64

Because we rely on pvcreate, vgcreate family of commands.

I'm not sure if I understand you correctly, correct me if I'm wrong.

**Comment by y0hnn** [comment]
Of course you are, but pip is just for installing python packages, isn't it ? Because this one must be a linux dependency, not a python one.

**Comment by sac** [comment]
@yohannprigent thanks for pointing it out. Commit: https://github.com/gluster/gdeploy/commit/b3cb138399d2f3603cac06ec340e3b42b3f428ed should fix it.

**Comment by sac** [comment]
I've updated INSTALL.md pointing users to install lvm2. However for rpm users, it is marked as a dependency.
