### ISSUE TITLE
firewalld has to be started for gdeploy to succeed

### ISSUE THREAD

**Issue by mykaul** [gluster/gdeploy#54]
It's not mentioned anywhere in the documentation and gdeploy does not ensure firewalld is up and running. If it isn't, gdeploy fails.

**Comment by sac-urs** [comment]
Yaniv, we will document that firewalld should be enabled in the config using the [service] configuration.

**Comment by nandajavarma** [comment]
@gluster-deploy As the work-around suggested by you seems satisfactory, shall I close this bug?

**Comment by satheesaran** [comment]
@nandajavarma - I would recommend closing this issue once the documentation that firewalld should be enabled in config is available

**Comment by sac** [comment]
Made changes as per first comment. Now if firewalld is used, gdeploy starts the daemon before applying rules.
