### ISSUE TITLE
Unable to create multiple vgs using gdeploy-3.0.0

### ISSUE THREAD

**Issue by pkesavap** [gluster/gdeploy#544]
The gdeploy branch 3.0.0 is unable to create multiple vgs in the same backend setup, i have attached the conf file and the ansilbe-output file. It was unable to create pv, but instead of ',' when given space it worked fine. 
[OUTPUTFILE][op.txt](https://github.com/gluster/gdeploy/files/4259900/op.txt)
[CONF FILE][gdeploy2.txt](https://github.com/gluster/gdeploy/files/4259909/gdeploy2.txt)

**Comment by sac** [comment]
The conf file is wrong. The vgs, pvs, and any other value has to be comma separated. Please restest with changes.

**Comment by pkesavap** [comment]
> The conf file is wrong. The vgs, pvs, and any other value has to be comma separated. Please restest with changes.

Hey @sac , it was tested with proper conf file with commas as mentioned, still the problem existed
The problem was it was not properly parsing and looping across the list of items passed, because in 3.0.0,  when there was a line which erases __name__ from list it threw an exception, because "__name__" was not there in the first place, and since this exception was not properly handled, other methods which was responsible for parsing  values from config was not called.

**Comment by gobindadas** [comment]
Prajit can you please add the eaxample of conf file which was failing?

**Comment by gobindadas** [comment]
@sac Here is the conf file which was failing

The following conf file was failing
[Hosts]
host.hostname.com
[backend-setup]
devices=/dev/sdb,/dev/sdc
vgs=vg0,vg1
pools=pool0,pool1
lvs=lv0,lv1
brick_dirs=/bricks/brick0,/bricks/brick1

**Comment by gobindadas** [comment]
As scratch build is working as expected, so merging this.

**Comment by pkesavap** [comment]
fixed the issue

PR:https://github.com/gluster/gdeploy/pull/545
