### ISSUE TITLE
gdeploy creates a lot of empty repos

### ISSUE THREAD

**Issue by mykaul** [gluster/gdeploy#55]
Using branch 2.0:

ls -l /etc/yum.repos.d/ |less

rw-r--r--. 1 root root    0 Apr  3 14:34 _
-rw-r--r--. 1 root root    0 Apr  3 14:34 -
-rw-r--r--. 1 root root    0 Apr  3 14:34 :
-rw-r--r--. 1 root root    0 Apr  3 14:34 4
-rw-r--r--. 1 root root   43 Apr  3 14:34 4.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 6
-rw-r--r--. 1 root root   43 Apr  3 14:34 6.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 7
-rw-r--r--. 1 root root   43 Apr  3 14:34 7.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 8
-rw-r--r--. 1 root root   43 Apr  3 14:34 8.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 a
-rw-r--r--. 1 root root   43 Apr  3 14:34 a.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 b
-rw-r--r--. 1 root root   43 Apr  3 14:34 b.repo
-rw-r--r--. 1 root root 1664 Dec  9 04:59 CentOS-Base.repo
-rw-r--r--. 1 root root 1309 Dec  9 04:59 CentOS-CR.repo
-rw-r--r--. 1 root root  649 Dec  9 04:59 CentOS-Debuginfo.repo
-rw-r--r--. 1 root root  290 Dec  9 04:59 CentOS-fasttrack.repo
-rw-r--r--. 1 root root  630 Dec  9 04:59 CentOS-Media.repo
-rw-r--r--. 1 root root 1331 Dec  9 04:59 CentOS-Sources.repo
-rw-r--r--. 1 root root 1952 Dec  9 04:59 CentOS-Vault.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 d
-rw-r--r--. 1 root root   43 Apr  3 14:34 d.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 e
-rw-r--r--. 1 root root   43 Apr  3 14:34 e.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 f
-rw-r--r--. 1 root root   43 Apr  3 14:34 f.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 g
-rw-r--r--. 1 root root   43 Apr  3 14:34 g.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 h
-rw-r--r--. 1 root root   43 Apr  3 14:34 h.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 i
-rw-r--r--. 1 root root   43 Apr  3 14:34 i.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 l
-rw-r--r--. 1 root root  123 Apr  3 14:33 local-ovirt.repo
-rw-r--r--. 1 root root   43 Apr  3 14:34 l.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 n
-rw-r--r--. 1 root root   43 Apr  3 14:34 n.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 o
-rw-r--r--. 1 root root   43 Apr  3 14:34 o.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 p
-rw-r--r--. 1 root root   43 Apr  3 14:34 p.repo
-rw-r--r--. 1 root root    0 Apr  3 14:34 r
-rw-r--r--. 1 root root   43 Apr  3 14:34 _.repo
-rw-r--r--. 1 root root   43 Apr  3 14:34 -.repo
-rw-r--r--. 1 root root   43 Apr  3 14:34 :.repo
-rw-r--r--. 1 root root   43 Apr  3 14:34 r.repo
...

**Comment by nandajavarma** [comment]
The above commit fixes the issue.

**Comment by mykaul** [comment]
@nandajavarma this is not fixed - just tested with 3e48fbed4d8cd0d2329f0d57461424ab191fcb62 (2.0 branch) - still seeing all those dirs.

**Comment by nandajavarma** [comment]
@mykaul Please provide the configuration file for us to reproduce.

**Comment by mykaul** [comment]
Note that my script, before running, converts the hosts to IPs, otherwise things don't work:

[hosts]
lago_basic_suite_hc_host0
lago_basic_suite_hc_host1
lago_basic_suite_hc_host2

[backend-setup]
devices=/dev/vdb,/dev/vdc,/dev/vdd
mountpoints=/mnt/engine,/mnt/vmstore,/mnt/data

[yum]
action=install
gpgcheck=no
repos=http://download.gluster.org/pub/gluster/glusterfs/nightly/glusterfs/epel-7-x86_64
packages=vdsm,vdsm-gluster,ovirt-hosted-engine-setup,screen,gluster-nagios-addons,xauth
update=yes

[service1]
action=restart
service=glusterd

[service2]
action=stop
service=multipathd

[service3]
action=disable
service=multipathd

[firewalld]
action=add
ports=111/tcp,2049/tcp,54321/tcp,5900/tcp,5900-6923/tcp,5666/tcp,16514/tcp
services=glusterfs,dhcp

[selinux]
yes

[update-file]
action=edit
dest=/etc/nagios/nrpe.cfg
replace=allowed_hosts
line=allowed_hosts='host.redhat.com'

[service4]
action=restart
service=nrpe

[script]
action=execute
file=/tmp/hc-setup.sh

# Create GlusterFS volumes on the nodes

[volume1]
action=create
volname=engine
transport=tcp,rdma
replica=yes
replica_count=3
force=yes
key=group,storage.owner-uid,storage.owner-gid,features.shard,features.shard-block-size,performance.low-prio-threads,cluster.data-self-heal-algorithm
value=virt,36,36,on,512MB,32,full
brick_dirs=/mnt/engine/brick

[volume2]
action=create
volname=vmstore
transport=tcp,rdma
replica=yes
replica_count=3
force=yes
key=group,storage.owner-uid,storage.owner-gid,features.shard,features.shard-block-size,performance.low-prio-threads,cluster.data-self-heal-algorithm
value=virt,36,36,on,512MB,32,full
brick_dirs=/mnt/vmstore/brick

[volume3]
action=create
volname=data
transport=tcp,rdma
replica=yes
replica_count=3
force=yes
key=group,storage.owner-uid,storage.owner-gid,features.shard,features.shard-block-size,performance.low-prio-threads,cluster.data-self-heal-algorithm
value=virt,36,36,on,512MB,32,full
brick_dirs=/mnt/data/brick

**Comment by nandajavarma** [comment]
Thanks a lot for this report. Adding repos using 'yum' was one feature that was not extensively tested. Hope the current patch (https://github.com/gluster/gdeploy/commit/44251a88b94b265ce2142890febd0dac4cf0f2cc)  fixes it.
