### ISSUE TITLE
Gluster is stopped 4 times during gdeploy

### ISSUE THREAD

**Issue by mykaul** [gluster/gdeploy#56]
Surely there's a more efficient way to deploy Gluster:

[root@lago_basic_suite_hc_host0 ~]# grep "Stopped GlusterFS" /var/log/messages 
Apr  3 14:42:40 lago_basic_suite_hc_host0 systemd: Stopped GlusterFS, a clustered file-system server.
Apr  3 14:42:58 lago_basic_suite_hc_host0 systemd: Stopped GlusterFS, a clustered file-system server.
Apr  3 14:43:20 lago_basic_suite_hc_host0 systemd: Stopped GlusterFS, a clustered file-system server.
Apr  3 14:43:42 lago_basic_suite_hc_host0 systemd: Stopped GlusterFS, a clustered file-system server.

**Comment by nandajavarma** [comment]
The above commits fixes the issue.
