### ISSUE TITLE
gdeploy always exits with return code 0 - even if it fails

### ISSUE THREAD

**Issue by mykaul** [gluster/gdeploy#57]
Even if gdeploy fails, it seems like the return code for it is zero.

**Comment by nandajavarma** [comment]
gdeploy works in two steps:
1. Parsing the user configuration and creating some variable files.
2. Giving control over to ansible-playbook by passing corresponding playbook.
The control of the first part is upto us, where as once it is passed on to ansible, getting the return value to the gdeploy framework is impossible.  The zero return code is the return value of the gdeploy framework itself where it creates the variable file without errors. 
This makes testing and other things difficult, but as of now Ansible does not provide a way to deal with this.  If you look into other deployments that involves Ansible playbooks, you will realize that none of them actually have return codes. It is out of the scope of gdeploy to deal with this issue.
Hence closing this.
