### ISSUE TITLE
lv creation fails

### ISSUE THREAD

**Issue by mykaul** [gluster/gdeploy#58]
Regression:
PLAY [gluster_servers] *******************************************************\* 

TASK: [Create logical volume named metadata] *********************************\* 
<192.168.200.2> REMOTE_MODULE lv action=create lvname=metadata compute=rhs lvtype='thick' snapshot_reserve="0" vgname=GLUSTER_vg1
failed: [192.168.200.2] => (item=GLUSTER_vg1) => {"failed": true, "item": "GLUSTER_vg1"}
msg:   --size may not be zero.
  Run `lvcreate --help' for more information.

...ignoring
<192.168.200.2> REMOTE_MODULE lv action=create lvname=metadata compute=rhs lvtype='thick' snapshot_reserve="0" vgname=GLUSTER_vg2
failed: [192.168.200.2] => (item=GLUSTER_vg2) => {"failed": true, "item": "GLUSTER_vg2"}
msg:   --size may not be zero.
  Run `lvcreate --help' for more information.

I'm running with latest code - f2f15d4188e5bced350f938d5613677af3ef1222

**Comment by nandajavarma** [comment]
Can I have the configuration file, please?

**Comment by mykaul** [comment]
# Configuration file for setting up ROBO

[hosts]
lago_basic_suite_hc_host0
lago_basic_suite_hc_host1
lago_basic_suite_hc_host2

[backend-setup]
devices=/dev/vdb,/dev/vdc,/dev/vdd
mountpoints=/mnt/engine,/mnt/vmstore,/mnt/data

[yum]
action=install
gpgcheck=no
repos=http://download.gluster.org/pub/gluster/glusterfs/nightly/glusterfs/epel-7-x86_64
packages=vdsm,vdsm-gluster,ovirt-hosted-engine-setup,screen,gluster-nagios-addons,xauth
update=yes

[service1]
action=restart
service=glusterd

[service2]
action=stop
service=multipathd

[service3]
action=disable
service=multipathd

[firewalld]
action=add
ports=111/tcp,2049/tcp,54321/tcp,5900/tcp,5900-6923/tcp,5666/tcp,16514/tcp
services=glusterfs,dhcp

[selinux]
yes

[update-file]
action=edit
dest=/etc/nagios/nrpe.cfg
replace=allowed_hosts
line=allowed_hosts='host.redhat.com'

[service4]
action=restart
service=nrpe

[script]
action=execute
file=/tmp/hc-setup.sh

# Create GlusterFS volumes on the nodes

[volume1]
action=create
volname=engine
transport=tcp,rdma
replica=yes
replica_count=3
force=yes
key=group,storage.owner-uid,storage.owner-gid,features.shard,features.shard-block-size,performance.low-prio-threads,cluster.data-self-heal-algorithm
value=virt,36,36,on,512MB,32,full
brick_dirs=/mnt/engine/brick

[volume2]
action=create
volname=vmstore
transport=tcp,rdma
replica=yes
replica_count=3
force=yes
key=group,storage.owner-uid,storage.owner-gid,features.shard,features.shard-block-size,performance.low-prio-threads,cluster.data-self-heal-algorithm
value=virt,36,36,on,512MB,32,full
brick_dirs=/mnt/vmstore/brick

[volume3]
action=create
volname=data
transport=tcp,rdma
replica=yes
replica_count=3
force=yes
key=group,storage.owner-uid,storage.owner-gid,features.shard,features.shard-block-size,performance.low-prio-threads,cluster.data-self-heal-algorithm
value=virt,36,36,on,512MB,32,full
brick_dirs=/mnt/data/brick

[shell:lago_basic_suite_hc_host0]
action=execute
command=hosted-engine --deploy --otopi-environment='OVEHOSTED_CORE/screenProceed=bool:True --config-append=/tmp/hosted-engine-answer-file.conf

**Comment by sac** [comment]
Fixed this error in master. Available in latest release.
