### ISSUE TITLE
conf file should take as selinux is enabled for CentOS/RHEL/Fedora 

### ISSUE THREAD

**Issue by satheesaran** [gluster/gdeploy#61]
As of now, the configuration file assumes that selinux is disabled by default and doesn't provides selinux labels for the bricks by default.

It would be highly recommended that selinux is always enabled.
gdeploy should go with the default value of selinux as enabled

**Comment by sac** [comment]
@satheesaran I need more context here. We set: semanage fcontext -a -t glusterd_brick_t ...
This is done if you use [backend-setup] section. Let me know if you are referring something else.

**Comment by juanluisvaladas** [comment]
I believe @satheesaran means if you have selinux enabled gdeploy should set the propper context unless you write a section:

```
[selinux]
no
```

Right now it won't set the context *unless* you explicitely write selinux yes.

**Comment by satheesaran** [comment]
@juanluisvaladas Thanks for getting me right. I meant the same
@sac gdeploy should set selinux=enable by default, unless its mentioned as 'no' explicitly

**Comment by sac** [comment]
@satheesaran ACK!

**Comment by sac** [comment]
Commit: https://github.com/gluster/gdeploy/commit/d4a5f12ee0f resolves the issue.
