### ISSUE TITLE
update_file should also provide 'delete_file' and 'delete_line'

### ISSUE THREAD

**Issue by satheesaran** [gluster/gdeploy#62]
update_file provides options to copy, edit, add.
delete a file and deleting a line in a file would also be helpful

**Comment by devyanikota** [comment]
Am looking into this issue. will work on it !

**Comment by devyanikota** [comment]
PRs #336  #338  #341 resolve this issue.
@sac can you take a look at the same, else
we can close this issue. thanks.

**Comment by sac** [comment]
@devyanikota looks good. We can close this.
